CREATE TABLE equipamento (
	id BIGINT(20) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	codigo VARCHAR(20) NOT NULL,
	nome VARCHAR(50) NOT NULL,
	preco DECIMAL(9, 2) NOT NULL,
	modelo VARCHAR(20) NOT NULL,
	id_deposito BIGINT(20) NOT NULL,
	FOREIGN KEY (id_deposito) REFERENCES deposito(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
